# keep-sorted start
[
  ./aerc.nix
  ./alacritty.nix
  ./atuin.nix
  ./bat.nix
  ./bottom.nix
  ./broot.nix
  ./btop.nix
  ./cava.nix
  ./delta.nix
  ./dunst.nix
  ./element-desktop.nix
  ./eza.nix
  ./fcitx5.nix
  ./firefox.nix
  ./fish.nix
  ./foot.nix
  ./fuzzel.nix
  ./fzf.nix
  ./gh-dash.nix
  ./ghostty.nix
  ./gitui.nix
  ./glamour.nix
  ./halloy.nix
  ./helix.nix
  ./hyprland.nix
  ./hyprlock.nix
  ./imv.nix
  ./k9s.nix
  ./kitty.nix
  ./kvantum.nix
  ./lazygit.nix
  ./lsd.nix
  ./mako.nix
  ./mangohud.nix
  ./micro.nix
  ./mpv.nix
  ./newsboat.nix
  ./nushell.nix
  ./polybar.nix
  ./qutebrowser.nix
  ./rio.nix
  ./rofi.nix
  ./sioyek.nix
  ./skim.nix
  ./spotify-player.nix
  ./starship.nix
  ./sway.nix
  ./swaync.nix
  ./swaylock.nix
  ./television.nix
  ./tmux.nix
  ./tofi.nix
  ./vscode.nix
  ./waybar.nix
  ./wezterm.nix
  ./wleave.nix
  ./wlogout.nix
  ./xfce4-terminal.nix
  ./yazi.nix
  ./zathura.nix
  ./zed-editor.nix
  ./zsh-syntax-highlighting.nix
  ./anki.nix
  ./chrome.nix
  ./cursors.nix
  ./freetube.nix
  ./gemini-cli.nix
  ./gtk.nix
  ./neovim.nix
  ./obs.nix
  ./opencode.nix
  ./qt5ct.nix
  ./thunderbird.nix
  ./vesktop.nix
  ./vicinae.nix
  ./vivid.nix
  ./zellij.nix
]
# keep-sorted end
