name: Deploy Docs

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build Search Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: nix-themes
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build search site
        run: nix build ./dev#search --no-write-lock-file

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: result/

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
